/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ostrich33 (https://sketchfab.com/ostrich33)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/baseball-2880e9e69f274f4b8505db2f06240963
title: baseball
*/

import * as THREE from 'three'
import React, { useRef, useContext, useEffect } from 'react'
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';
import { BaseballContext } from './BaseballContext';

type GLTFResult = GLTF & {
  nodes: {
    baseball_pasted__baseball_sh_0: THREE.Mesh
    stitch_pasted__stitch_sh_0: THREE.Mesh
  }
  materials: {
    pasted__baseball_sh: THREE.MeshStandardMaterial
    pasted__stitch_sh: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/baseball.glb') as GLTFResult

  const { pitch, isRightHandedPitcher } = useContext(BaseballContext);

  const handle4SeamFastballRotation = () => {
    group.current?.rotateZ(isRightHandedPitcher ? -.15 : .15);
  }

  const handle2SeamFastballRotation = () => {
    group.current?.rotateX(-.15);
  }

  const handleCurveballRotation = () => {
    group.current?.rotateZ(isRightHandedPitcher ? .1 : -.1);
  }

  const handleSliderRotation = () => {
    group.current?.rotateZ(.2)
  }

  useEffect(() => {
    if(pitch) {
      const rotate45Deg = Math.PI/180 * 45;
      const rotate90Deg = Math.PI/180 * 90;
      group.current?.rotation.set(0,0,0);
      if(pitch === '2_SEAM_FASTBALL' || pitch === 'SLIDER') {
        group.current?.rotateZ(isRightHandedPitcher ? rotate45Deg: -rotate45Deg);
      } else if(pitch === '4_SEAM_FASTBALL' || pitch === 'CURVEBALL') {
        group.current?.rotateZ(isRightHandedPitcher? rotate45Deg: -rotate45Deg);
        group.current?.rotateY(isRightHandedPitcher? rotate90Deg: -rotate90Deg);
      }
    } 
  }, [pitch, isRightHandedPitcher])

  useFrame((state, delta) => {
    if(pitch === '4_SEAM_FASTBALL') {
      handle4SeamFastballRotation();
    } else if(pitch === '2_SEAM_FASTBALL') {
      handle2SeamFastballRotation();
    } else if(pitch === 'CURVEBALL') {
      handleCurveballRotation();
    } else if(pitch === 'SLIDER') {
      handleSliderRotation();
    }
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <mesh
        geometry={nodes.baseball_pasted__baseball_sh_0.geometry}
        material={materials.pasted__baseball_sh}
        position={0}
      />
      <mesh
        geometry={nodes.stitch_pasted__stitch_sh_0.geometry}
        material={materials.pasted__stitch_sh}
        position={0}
      />
    </group>
  )
}

useGLTF.preload('/baseball.glb')
