/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: NintendObi-Wan (https://sketchfab.com/NOW3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/8k-realistic-baseball-by-polyhaven-1a7346e0575149abab9fac3184dc94c3
title: 8K Realistic Baseball (By Polyhaven)
*/

import { Mesh, MeshStandardMaterial, Group } from 'three';
import { useRef, useContext, useEffect } from 'react'
import * as drei from '@react-three/drei';
import * as threeStdlib from 'three-stdlib';
import * as fiber from '@react-three/fiber';
import * as BaseballContext from './BaseballContext'

type GLTFResult = threeStdlib.GLTF & {
  nodes: {
    mesh_0: Mesh
  }
  materials: {
    baseball_01: MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<Group>()
  const { nodes, materials } = drei.useGLTF('/baseball.glb') as GLTFResult
  const { pitch, isRightHandedPitcher, rotationsPerSecond } = useContext(BaseballContext.BaseballContext);

  const handle4SeamFastballRotation = () => {
    var speed = Number((359 * rotationsPerSecond) * Math.PI/180);
    group.current?.rotateZ(isRightHandedPitcher ? speed : -speed);
  }

  const handle2SeamFastballRotation = () => {
    group.current?.rotateX(Number((359 * rotationsPerSecond) * Math.PI/180));
  }

  const handleCurveballRotation = () => {
    var speed = Number((359 * rotationsPerSecond) * Math.PI/180);
    group.current?.rotateZ(isRightHandedPitcher ? -speed : speed);
  }

  const handleSliderRotation = () => {
    var ySpeed = Number((359 * (rotationsPerSecond - 5)) * Math.PI/180);
    var zSpeed = Number((359 * rotationsPerSecond) * Math.PI/180);
    group.current?.rotateZ(isRightHandedPitcher ? -zSpeed : zSpeed);
    group.current?.rotateY(isRightHandedPitcher ? -ySpeed: ySpeed);
  }

  const handleChangeupRotation = () => {
    var speed = Number((359 * rotationsPerSecond) * Math.PI/180);
    group.current?.rotateZ(isRightHandedPitcher ? speed : -speed);
  }

  useEffect(() => {
    if(pitch) {
      group.current?.rotation.set(0,0,0);
      const rotate45Deg = Math.PI/180 * 45;
      const rotate90Deg = Math.PI/180 * 90;
      if(pitch === '2_SEAM_FASTBALL') {
        group.current?.rotateZ(isRightHandedPitcher ? rotate45Deg: -rotate45Deg);
      } else if(pitch === '4_SEAM_FASTBALL' || pitch === 'CURVEBALL' || pitch === 'CHANGEUP') {
        group.current?.rotateZ(isRightHandedPitcher ? rotate45Deg: -rotate45Deg);
        group.current?.rotateY(isRightHandedPitcher ? rotate90Deg: -rotate90Deg);
      } else if(pitch === 'SLIDER') {
        group.current?.rotateZ(isRightHandedPitcher ? rotate45Deg: -rotate45Deg);
      }
    } 
  }, [pitch, isRightHandedPitcher])

  fiber.useFrame((_state: any, _delta: any) => {
    if(pitch === '4_SEAM_FASTBALL') {
      handle4SeamFastballRotation();
    } else if(pitch === '2_SEAM_FASTBALL') {
      handle2SeamFastballRotation();
    } else if(pitch === 'CURVEBALL') {
      handleCurveballRotation();
    } else if(pitch === 'SLIDER') {
      handleSliderRotation();
    } else if(pitch === 'CHANGEUP') {
      handleChangeupRotation();
    }
  });
  return (
    <Group ref={group} {...props} dispose={null}>
          <Mesh geometry={nodes.mesh_0.geometry} material={materials.baseball_01} />
    </Group>
  )
}

drei.useGLTF.preload('/baseball.glb')